# Generated by Django 4.1.2 on 2023-06-03 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_system', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resto_menu',
            name='item_price',
            field=models.IntegerField(max_length=50),
        ),
    ]
