# Generated by Django 4.1.2 on 2023-06-04 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_system', '0002_alter_resto_menu_item_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_bed_quantity',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_capacity',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_number',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_price',
            field=models.IntegerField(),
        ),
    ]
