# Generated by Django 4.1.2 on 2023-06-05 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_system', '0007_invoices'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Invoices',
        ),
    ]
