# Generated by Django 4.1.2 on 2023-06-05 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_system', '0008_delete_invoices'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inv_no', models.IntegerField()),
                ('inv_user_name', models.CharField(max_length=100)),
                ('inv_room_name', models.CharField(max_length=100)),
                ('inv_price', models.IntegerField(default=True)),
                ('inv_room_no', models.IntegerField(default=True)),
                ('inv_check_in_date', models.DateField()),
                ('Inv_check_out_date', models.DateField()),
            ],
        ),
    ]
