# Generated by Django 4.1.2 on 2023-06-05 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_system', '0010_remove_invoices_inv_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoices',
            name='inv_user_email',
            field=models.EmailField(max_length=50, null=True),
        ),
    ]
